# Generated by Django 4.2.5 on 2023-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoupload', '0002_video_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('chunk_number', models.PositiveIntegerField()),
                ('total_chunks', models.PositiveIntegerField()),
                ('video_chunk', models.FileField(upload_to='video_chunks/')),
            ],
        ),
    ]
